/*
Portions of this file are copied from the SDL3 headers. The SDL3 license is
reproduced below:

This software is provided 'as-is', without any express or implied
warranty.  In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.
*/

package sdl

// #cgo pkg-config: sdl3
// #include <SDL3/SDL.h>
import "C"

// # CategoryKeycode
//
// Defines constants which identify keyboard keys and modifiers.
//
// Please refer to the Best Keyboard Practices docment for details on what
// this information means and how best to use it.
//
// https://wiki.libsdl.org/SDL3/BestKeyboardPractices

// The SDL virtual key representation.
//
// Values of this type are used to represent keyboard keys using the current
// layout of the keyboard. These values include Unicode values representing
// the unmodified character that would be generated by pressing the key, or an
// `SDLK_*` constant for those keys that do not generate characters.
//
// A special exception is the number keys at the top of the keyboard which map
// to SDLK_0...SDLK_9 on AZERTY layouts.
//
// Keys with the `SDLK_EXTENDED_MASK` bit set do not map to a scancode or
// unicode code point.
//
// This datatype is available since SDL 3.2.0.
//
// https://wiki.libsdl.org/SDL3/SDL_Keycode
type Keycode uint32

const KeyExtendedMask Keycode = 1 << 29
const KeyScancodeMask Keycode = 1 << 30

// https://wiki.libsdl.org/SDL3/SDL_SCANCODE_TO_KEYCODE
func (s Scancode) ToKeycode() Keycode {
	return Keycode(s) | KeyScancodeMask
}

const (
	KeyUnknown            Keycode = 0x00000000 //0
	KeyReturn             Keycode = 0x0000000d //'\r'
	KeyEscape             Keycode = 0x0000001b //'\x1B'
	KeyBackspace          Keycode = 0x00000008 //'\b'
	KeyTab                Keycode = 0x00000009 //'\t'
	KeySpace              Keycode = 0x00000020 //' '
	KeyExclaim            Keycode = 0x00000021 //'!'
	KeyDblapostrophe      Keycode = 0x00000022 //'"'
	KeyHash               Keycode = 0x00000023 //'#'
	KeyDollar             Keycode = 0x00000024 //'$'
	KeyPercent            Keycode = 0x00000025 //'%'
	KeyAmpersand          Keycode = 0x00000026 //'&'
	KeyApostrophe         Keycode = 0x00000027 //'\''
	KeyLeftparen          Keycode = 0x00000028 //'('
	KeyRightparen         Keycode = 0x00000029 //')'
	KeyAsterisk           Keycode = 0x0000002a //'*'
	KeyPlus               Keycode = 0x0000002b //'+'
	KeyComma              Keycode = 0x0000002c //','
	KeyMinus              Keycode = 0x0000002d //'-'
	KeyPeriod             Keycode = 0x0000002e //'.'
	KeySlash              Keycode = 0x0000002f //'/'
	Key0                  Keycode = 0x00000030 //'0'
	Key1                  Keycode = 0x00000031 //'1'
	Key2                  Keycode = 0x00000032 //'2'
	Key3                  Keycode = 0x00000033 //'3'
	Key4                  Keycode = 0x00000034 //'4'
	Key5                  Keycode = 0x00000035 //'5'
	Key6                  Keycode = 0x00000036 //'6'
	Key7                  Keycode = 0x00000037 //'7'
	Key8                  Keycode = 0x00000038 //'8'
	Key9                  Keycode = 0x00000039 //'9'
	KeyColon              Keycode = 0x0000003a //':'
	KeySemicolon          Keycode = 0x0000003b //';'
	KeyLess               Keycode = 0x0000003c //'<'
	KeyEquals             Keycode = 0x0000003d //'='
	KeyGreater            Keycode = 0x0000003e //'>'
	KeyQuestion           Keycode = 0x0000003f //'?'
	KeyAt                 Keycode = 0x00000040 //'@'
	KeyLeftbracket        Keycode = 0x0000005b //'['
	KeyBackslash          Keycode = 0x0000005c //'\\'
	KeyRightbracket       Keycode = 0x0000005d //']'
	KeyCaret              Keycode = 0x0000005e //'^'
	KeyUnderscore         Keycode = 0x0000005f //'_'
	KeyGrave              Keycode = 0x00000060 //'`'
	KeyA                  Keycode = 0x00000061 //'a'
	KeyB                  Keycode = 0x00000062 //'b'
	KeyC                  Keycode = 0x00000063 //'c'
	KeyD                  Keycode = 0x00000064 //'d'
	KeyE                  Keycode = 0x00000065 //'e'
	KeyF                  Keycode = 0x00000066 //'f'
	KeyG                  Keycode = 0x00000067 //'g'
	KeyH                  Keycode = 0x00000068 //'h'
	KeyI                  Keycode = 0x00000069 //'i'
	KeyJ                  Keycode = 0x0000006a //'j'
	KeyK                  Keycode = 0x0000006b //'k'
	KeyL                  Keycode = 0x0000006c //'l'
	KeyM                  Keycode = 0x0000006d //'m'
	KeyN                  Keycode = 0x0000006e //'n'
	KeyO                  Keycode = 0x0000006f //'o'
	KeyP                  Keycode = 0x00000070 //'p'
	KeyQ                  Keycode = 0x00000071 //'q'
	KeyR                  Keycode = 0x00000072 //'r'
	KeyS                  Keycode = 0x00000073 //'s'
	KeyT                  Keycode = 0x00000074 //'t'
	KeyU                  Keycode = 0x00000075 //'u'
	KeyV                  Keycode = 0x00000076 //'v'
	KeyW                  Keycode = 0x00000077 //'w'
	KeyX                  Keycode = 0x00000078 //'x'
	KeyY                  Keycode = 0x00000079 //'y'
	KeyZ                  Keycode = 0x0000007a //'z'
	KeyLeftbrace          Keycode = 0x0000007b //'{'
	KeyPipe               Keycode = 0x0000007c //'|'
	KeyRightbrace         Keycode = 0x0000007d //'}'
	KeyTilde              Keycode = 0x0000007e //'~'
	KeyDelete             Keycode = 0x0000007f //'\x7F'
	KeyPlusminus          Keycode = 0x000000b1 //'\xB1'
	KeyCapslock           Keycode = 0x40000039 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK)
	KeyF1                 Keycode = 0x4000003a //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1)
	KeyF2                 Keycode = 0x4000003b //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2)
	KeyF3                 Keycode = 0x4000003c //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3)
	KeyF4                 Keycode = 0x4000003d //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4)
	KeyF5                 Keycode = 0x4000003e //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5)
	KeyF6                 Keycode = 0x4000003f //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6)
	KeyF7                 Keycode = 0x40000040 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7)
	KeyF8                 Keycode = 0x40000041 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8)
	KeyF9                 Keycode = 0x40000042 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9)
	KeyF10                Keycode = 0x40000043 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10)
	KeyF11                Keycode = 0x40000044 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11)
	KeyF12                Keycode = 0x40000045 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12)
	KeyPrintscreen        Keycode = 0x40000046 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN)
	KeyScrolllock         Keycode = 0x40000047 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK)
	KeyPause              Keycode = 0x40000048 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE)
	KeyInsert             Keycode = 0x40000049 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT)
	KeyHome               Keycode = 0x4000004a //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME)
	KeyPageup             Keycode = 0x4000004b //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP)
	KeyEnd                Keycode = 0x4000004d //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END)
	KeyPagedown           Keycode = 0x4000004e //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN)
	KeyRight              Keycode = 0x4000004f //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT)
	KeyLeft               Keycode = 0x40000050 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT)
	KeyDown               Keycode = 0x40000051 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN)
	KeyUp                 Keycode = 0x40000052 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP)
	KeyNumlockclear       Keycode = 0x40000053 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR)
	KeyKPDivide           Keycode = 0x40000054 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE)
	KeyKPMultiply         Keycode = 0x40000055 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY)
	KeyKPMinus            Keycode = 0x40000056 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS)
	KeyKPPlus             Keycode = 0x40000057 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS)
	KeyKPEnter            Keycode = 0x40000058 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER)
	KeyKP1                Keycode = 0x40000059 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1)
	KeyKP2                Keycode = 0x4000005a //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2)
	KeyKP3                Keycode = 0x4000005b //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3)
	KeyKP4                Keycode = 0x4000005c //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4)
	KeyKP5                Keycode = 0x4000005d //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5)
	KeyKP6                Keycode = 0x4000005e //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6)
	KeyKP7                Keycode = 0x4000005f //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7)
	KeyKP8                Keycode = 0x40000060 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8)
	KeyKP9                Keycode = 0x40000061 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9)
	KeyKP0                Keycode = 0x40000062 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0)
	KeyKPPeriod           Keycode = 0x40000063 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD)
	KeyApplication        Keycode = 0x40000065 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION)
	KeyPower              Keycode = 0x40000066 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER)
	KeyKPEquals           Keycode = 0x40000067 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS)
	KeyF13                Keycode = 0x40000068 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F13)
	KeyF14                Keycode = 0x40000069 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F14)
	KeyF15                Keycode = 0x4000006a //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F15)
	KeyF16                Keycode = 0x4000006b //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F16)
	KeyF17                Keycode = 0x4000006c //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F17)
	KeyF18                Keycode = 0x4000006d //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F18)
	KeyF19                Keycode = 0x4000006e //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F19)
	KeyF20                Keycode = 0x4000006f //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F20)
	KeyF21                Keycode = 0x40000070 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F21)
	KeyF22                Keycode = 0x40000071 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F22)
	KeyF23                Keycode = 0x40000072 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F23)
	KeyF24                Keycode = 0x40000073 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F24)
	KeyExecute            Keycode = 0x40000074 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXECUTE)
	KeyHelp               Keycode = 0x40000075 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HELP)
	KeyMenu               Keycode = 0x40000076 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MENU)
	KeySelect             Keycode = 0x40000077 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SELECT)
	KeyStop               Keycode = 0x40000078 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_STOP)
	KeyAgain              Keycode = 0x40000079 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN)
	KeyUndo               Keycode = 0x4000007a //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UNDO)
	KeyCut                Keycode = 0x4000007b //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT)
	KeyCopy               Keycode = 0x4000007c //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY)
	KeyPaste              Keycode = 0x4000007d //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE)
	KeyFind               Keycode = 0x4000007e //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_FIND)
	KeyMute               Keycode = 0x4000007f //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE)
	KeyVolumeup           Keycode = 0x40000080 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP)
	KeyVolumedown         Keycode = 0x40000081 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN)
	KeyKPComma            Keycode = 0x40000085 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA)
	KeyKPEqualsas400      Keycode = 0x40000086 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400)
	KeyAlterase           Keycode = 0x40000099 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE)
	KeySysreq             Keycode = 0x4000009a //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ)
	KeyCancel             Keycode = 0x4000009b //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CANCEL)
	KeyClear              Keycode = 0x4000009c //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEAR)
	KeyPrior              Keycode = 0x4000009d //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRIOR)
	KeyReturn2            Keycode = 0x4000009e //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2)
	KeySeparator          Keycode = 0x4000009f //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SEPARATOR)
	KeyOut                Keycode = 0x400000a0 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT)
	KeyOper               Keycode = 0x400000a1 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER)
	KeyClearagain         Keycode = 0x400000a2 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN)
	KeyCrsel              Keycode = 0x400000a3 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL)
	KeyExsel              Keycode = 0x400000a4 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL)
	KeyKP00               Keycode = 0x400000b0 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00)
	KeyKP000              Keycode = 0x400000b1 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000)
	KeyThousandsseparator Keycode = 0x400000b2 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR)
	KeyDecimalseparator   Keycode = 0x400000b3 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR)
	KeyCurrencyunit       Keycode = 0x400000b4 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT)
	KeyCurrencysubnit     Keycode = 0x400000b5 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBNIT)
	KeyKPLeftparen        Keycode = 0x400000b6 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN)
	KeyKPRightparen       Keycode = 0x400000b7 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN)
	KeyKPLeftbrace        Keycode = 0x400000b8 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE)
	KeyKPRightbrace       Keycode = 0x400000b9 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE)
	KeyKPTab              Keycode = 0x400000ba //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_TAB)
	KeyKPBackspace        Keycode = 0x400000bb //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE)
	KeyKPA                Keycode = 0x400000bc //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A)
	KeyKPB                Keycode = 0x400000bd //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B)
	KeyKPC                Keycode = 0x400000be //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C)
	KeyKPD                Keycode = 0x400000bf //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D)
	KeyKPE                Keycode = 0x400000c0 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E)
	KeyKPF                Keycode = 0x400000c1 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F)
	KeyKPXor              Keycode = 0x400000c2 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR)
	KeyKPPower            Keycode = 0x400000c3 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER)
	KeyKPPercent          Keycode = 0x400000c4 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT)
	KeyKPLess             Keycode = 0x400000c5 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS)
	KeyKPGreater          Keycode = 0x400000c6 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER)
	KeyKPAmpersand        Keycode = 0x400000c7 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND)
	KeyKPDblampersand     Keycode = 0x400000c8 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND)
	KeyKPVerticalbar      Keycode = 0x400000c9 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR)
	KeyKPDblverticalbar   Keycode = 0x400000ca //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR)
	KeyKPColon            Keycode = 0x400000cb //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON)
	KeyKPHash             Keycode = 0x400000cc //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH)
	KeyKPSpace            Keycode = 0x400000cd //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE)
	KeyKPAt               Keycode = 0x400000ce //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT)
	KeyKPExclam           Keycode = 0x400000cf //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM)
	KeyKPMemstore         Keycode = 0x400000d0 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE)
	KeyKPMemrecall        Keycode = 0x400000d1 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL)
	KeyKPMemclear         Keycode = 0x400000d2 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR)
	KeyKPMemadd           Keycode = 0x400000d3 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD)
	KeyKPMemsubtract      Keycode = 0x400000d4 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT)
	KeyKPMemmultiply      Keycode = 0x400000d5 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY)
	KeyKPMemdivide        Keycode = 0x400000d6 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE)
	KeyKPPlusminus        Keycode = 0x400000d7 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS)
	KeyKPClear            Keycode = 0x400000d8 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR)
	KeyKPClearentry       Keycode = 0x400000d9 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY)
	KeyKPBinary           Keycode = 0x400000da //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY)
	KeyKPOctal            Keycode = 0x400000db //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL)
	KeyKPDecimal          Keycode = 0x400000dc //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL)
	KeyKPHexadecimal      Keycode = 0x400000dd //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL)
	KeyLeftCtrl           Keycode = 0x400000e0 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL)
	KeyLeftShift          Keycode = 0x400000e1 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT)
	KeyLeftAlt            Keycode = 0x400000e2 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT)
	KeyLeftGui            Keycode = 0x400000e3 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI)
	KeyRightCtrl          Keycode = 0x400000e4 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL)
	KeyRightShift         Keycode = 0x400000e5 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT)
	KeyRightAlt           Keycode = 0x400000e6 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT)
	KeyRightGui           Keycode = 0x400000e7 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI)
	KeyMode               Keycode = 0x40000101 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MODE)
	KeySleep              Keycode = 0x40000102 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP)
	KeyWake               Keycode = 0x40000103 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WAKE)
	KeyChannelIncrement   Keycode = 0x40000104 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_INCREMENT)
	KeyChannelDecrement   Keycode = 0x40000105 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_DECREMENT)
	KeyMediaPlay          Keycode = 0x40000106 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY)
	KeyMediaPase          Keycode = 0x40000107 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PASE)
	KeyMediaRecord        Keycode = 0x40000108 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_RECORD)
	KeyMediaFastForward   Keycode = 0x40000109 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_FAST_FORWARD)
	KeyMediaRewind        Keycode = 0x4000010a //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_REWIND)
	KeyMediaNextTrack     Keycode = 0x4000010b //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_NEXT_TRACK)
	KeyMediaPreviousTrack Keycode = 0x4000010c //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PREVIOUS_TRACK)
	KeyMediaStop          Keycode = 0x4000010d //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_STOP)
	KeyMediaEject         Keycode = 0x4000010e //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_EJECT)
	KeyMediaPlayPase      Keycode = 0x4000010f //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY_PASE)
	KeyMediaSelect        Keycode = 0x40000110 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_SELECT)
	KeyAcNew              Keycode = 0x40000111 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_NEW)
	KeyAcOpen             Keycode = 0x40000112 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_OPEN)
	KeyAcClose            Keycode = 0x40000113 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_CLOSE)
	KeyAcExit             Keycode = 0x40000114 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_EXIT)
	KeyAcSave             Keycode = 0x40000115 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SAVE)
	KeyAcPrint            Keycode = 0x40000116 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PRINT)
	KeyAcProperties       Keycode = 0x40000117 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PROPERTIES)
	KeyAcSearch           Keycode = 0x40000118 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH)
	KeyAcHome             Keycode = 0x40000119 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME)
	KeyAcBack             Keycode = 0x4000011a //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK)
	KeyAcForward          Keycode = 0x4000011b //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD)
	KeyAcStop             Keycode = 0x4000011c //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP)
	KeyAcRefresh          Keycode = 0x4000011d //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH)
	KeyAcBookmarks        Keycode = 0x4000011e //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS)
	KeySoftleft           Keycode = 0x4000011f //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTLEFT)
	KeySoftright          Keycode = 0x40000120 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTRIGHT)
	KeyCall               Keycode = 0x40000121 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALL)
	KeyEndcall            Keycode = 0x40000122 //SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ENDCALL)
	KeyLeftTab            Keycode = 0x20000001 //Extended key Left Tab
	KeyLevel5Shift        Keycode = 0x20000002 //Extended key Level 5 Shift
	KeyMultiKeyCompose    Keycode = 0x20000003 //Extended key Multi-key Compose
	KeyLeftMeta           Keycode = 0x20000004 //Extended key Left Meta
	KeyRightMeta          Keycode = 0x20000005 //Extended key Right Meta
	KeyLeftHyper          Keycode = 0x20000006 //Extended key Left Hyper
	KeyRightHyper         Keycode = 0x20000007 //Extended key Right Hyper
)

// Valid key modifiers (possibly OR'd together).
//
// This datatype is available since SDL 3.2.0.
//
// https://wiki.libsdl.org/SDL3/SDL_Keymod
type Keymod uint16

const (
	ModNone       Keymod = 0x0000 //no modifier is applicable.
	ModLeftShift  Keymod = 0x0001 //the left Shift key is down.
	ModRightShift Keymod = 0x0002 //the right Shift key is down.
	ModLevel5     Keymod = 0x0004 //the Level 5 Shift key is down.
	ModLeftCtrl   Keymod = 0x0040 //the left Ctrl (Control) key is down.
	ModRightCtrl  Keymod = 0x0080 //the right Ctrl (Control) key is down.
	ModLeftAlt    Keymod = 0x0100 //the left Alt key is down.
	ModRightAlt   Keymod = 0x0200 //the right Alt key is down.
	ModLeftGui    Keymod = 0x0400 //the left GUI key (often the Windows key) is down.
	ModRightGui   Keymod = 0x0800 //the right GUI key (often the Windows key) is down.
	ModNum        Keymod = 0x1000 //the Num Lock key (may be located on an extended keypad) is down.
	ModCaps       Keymod = 0x2000 //the Caps Lock key is down.
	ModMode       Keymod = 0x4000 //the !AltGr key is down.
	ModScroll     Keymod = 0x8000 //the Scroll Lock key is down.

	ModCtrl  Keymod = ModLeftCtrl | ModRightCtrl   // Any Ctrl key is down.
	ModShift Keymod = ModLeftShift | ModRightShift // Any Shift key is down.
	ModAlt   Keymod = ModLeftAlt | ModRightAlt     // Any Alt key is down.
	ModGui   Keymod = ModLeftGui | ModRightGui     // Any GUI key is down.
)
